# f=open("n&Ini.txt","r")
# for line in f:
#     print(line, end="")
# f.close()
# conty=f.read(12)
# print("1",conty)
# conty=f.read(10)
# print("2",conty)
t=open("n&Ini.txt","w")
t.write("Nandu is great")